---
- name: Install dnf dependencies
  dnf:
    name: "{{ item }}"
    state: present
  with_items: "{{ repo_dependencies }}"

- name: Create Downloads directory
  file:
    path: "/home/{{ user }}/Downloads"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0755

- name: Create .config directory
  file:
    path: ~/home/{{ user }}/.config
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0700

- name: Install JetBrainsMono NF
  block:
    - name: Create fonts directory
      file:
        path: "/home/{{ user }}/.local/share/fonts"
        state: directory
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: 0755

    - name: Download JetBrainsMono
      get_url:
        dest: "/home/{{ user }}/Downloads/JetBrainsMono.zip"
        url: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.3.0/JetBrainsMono.zip
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: 0644

    - name: Extract JetBrainsMono
      unarchive:
        src: "/home/{{ user }}/Downloads/JetBrainsMono.zip"
        dest: "/home/{{ user }}/.local/share/fonts"
        remote_src: yes

    - name: Refresh available fonts
      shell: "/usr/bin/fc-cache -rv"

- name: Shared sway config files
  block:
    - name: Create directories for shared files
      file:
        path: "{{ item }}"
        state: directory
        owner: root
        group: root
        mode: 0755
      with_items:
        - /usr/share/sway
        - /usr/share/sway/config.d
        - /usr/share/sway-systemd
        - /etc/sway
        - /etc/sway/config.d

    - name: Copy files to /usr/share/sway/config.d
      copy:
        src: "{{ item }}"
        dest: "/usr/share/sway/config.d/{{ item }}"
        owner: root
        group: root
        mode: 0644
      with_items: "{{ share_sway_configd }}"

    - name: Copy files to /usr/share/sway-systemd
      copy:
        src: "{{ item }}"
        dest: "/usr/share/sway-systemd/{{ item }}"
        owner: root
        group: root
        mode: 0644
      with_items: "{{ share_sway_systemd }}"

    - name: Copy files to /etc/sway/config.d
      copy:
        src: "{{ item }}"
        dest: "/etc/sway/config.d/{{ item }}"
        owner: root
        group: root
        mode: 0644
      with_items: "{{ etc_sway_configd }}"

    # Could also copy general contents of /etc/sway but we'll come back

- name: Configure sway
  block:

- name: Configure SDDM
  block:

- name: Configure kitty
  block:

- name: Configure waybar
  block:

- name: Configure dunst
  block:
