---
- name: Task 18
  hosts: database

  tasks:
    - name: Apply template
      template:
        src: ./server_list.j2
        dest: /etc/server_list.txt
        owner: automation
        group: automation
        mode: 0600
        setype: net_conf_t
