---
- name: Add or update user password
  user:
    name: george
    update_password: always
    password: "{{ newpassword|password_hash('sha512') }}"

# Run with:
# ansible-playbook update_password.yml --extra-vars newpassword=abc123
