---
- name: Change selinux parameters on webservers
  hosts: webservers
  become: yes

  vars:
    selinux_booleans:
      - name: httpd_can_network_connect
        state: true
        persistent: true

  roles:
    - rhel-system-roles.selinux
