---
- name: Download tomcat from tomcat.apache.org
  hosts: localhost

  tasks:
    - name: Create a directory for tomcat
      file:
        path: /opt/tomcat
        state: directory
        owner: root
        group: root
        mode: 755

    - name: Download tomcat using get_url
      get_url:
        url: https://dlcdn.apache.org/tomcat/...
        dest: /opt/tomcat
        owner: daniel
        group: daniel
        mode: 0755
