---
- name: Verify Apache Installation
  hosts: localhost

  tasks:
    - name: Install Apache
      yum:
        name: httpd
        state: present

    - name: Copy apache config
      copy:
        src: /tmp/httpd.conf
        dest: /etc/httpd.conf
      notify:
        - Restart Apache

    - name: Start Apache
      service:
        name: httpd
        state: started

  handlers:
    - name: Restart Apache
      service:
        name: httpd
        state: restarted

