---
- name: Copy a file to client
  hosts: localhost
  vars:
    srcfile: /home/daniel/tester

  tasks:
    - name: Copy file
      become: true
      copy:
        src: "{{ srcfile }}"
        dest: /tmp
        owner: daniel
        group: daniel
        mode: 0644
