---
- name: Install a package
  hosts: localhost
  vars:
    sespackage: somepackagewithanannoyingname
    # Better to use variables when theres a long or complicated name

  tasks:
    - name: Package install
      yum:
        name: "{{ sespackage }}"
        state: present

    - name: Start service
      service:
        name: "{{ sespackage }}"
        state: started

