---
- name: Full package install and setup
  hosts: localhost

  tasks:
    - name: Install Apache
      yum:
        name: httpd
        state: present

    - name: Start Apache
      service:
        name: httpd
        state: present

    - name: Open firewall port for apache
      firewalld:
        service: httpd
        state: enabled
        permanent: true

    - name: Restart the firewall
      service:
        name: firewalld
        state: reloaded
