---
- name: Configure server for database
  tasks:
    - name: Create partition for lvm
      parted:
        device: /dev/sdb
        number: 1
        flags: [ lvm ]
        part_end: 800MB
        state: present
        label: gpt

    - name: Create volume group
      lvg:
        vg: vg_database
        pvs: /dev/sdb1

    - name: Create logical volume
      lvol:
        vg: vg_database
        lv: lv_mysql
        state: present
        size: 512MB

    - name: Create filesystem
      filesystem:
        dev: /dev/mapper/vg_database-lv_mysql
        fstype: xfs

    - name: Mount lvm
      mount:
        src: /dev/mapper/vg_database-lv_mysql
        fstype: xfs
        path: /mnt/mysql_backups
        state: mounted
        opts: defaults

    - name: Install mariadb
      package:
        name: mariadb
        state: present

    - name: Open firewall for MySQL
      firewalld:
        permanent: true
        service: mysql
        immediate: true
        state: enabled
        port: 3306/TCP
