---
- name: Create a repository file
  hosts: all
  become: yes

  tasks:
    - name: Create the RPMS repo
      copy:
        dest: /etc/yum.repos.d/rpms.repo
        content: |
          [BaseOS]
          name=BaseOS on repo.ansi.example.com
          baseurl=http://repo.ansi.example.com/BaseOS
          gpgcheck=0
          enabled=1

          [AppStream]
          name=AppStream on repo.ansi.example.com
          baseurl=http://repo.ansi.example.com/AppStream
          gpgcheck=0
          enabled=1

    - name: Disable IPA repo
      lineinfile:
        path: /etc/yum.repos.d/ipa.repo
        regexp: "^enabled"
        line: "enabled=0"
      ignore_errors: yes
